# Generated by Django 4.1.6 on 2023-02-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='Date of booking')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
